services:
  user-service:
    build: ./Microservices/user-service
    ports:
      - "3000:3000"
  
  product-service:
    build: ./Microservices/product-service
    ports:
      - "3001:3001"
  
  order-service:
    build: ./Microservices/order-service
    ports:
      - "3002:3002"
  
  gateway-service:
    build: ./Microservices/gateway-service
    ports:
      - "3003:3003"
    depends_on:
      - user-service
      - product-service
      - order-service